import { deflateRawSync, inflateRawSync } from "node:zlib";
import { describe, expect, test } from "vitest";
import { createFflateFrameCompressionAdapter } from "./fflate-frame-compression.js";
import { MAX_COMPRESSION_INPUT_BYTES } from "./framed-ciphertext.js";

describe("fflate frame compression", () => {
  test("decodes a Node raw DEFLATE frame to the exact original bytes", async () => {
    /** Original bytes compressed by the independent Node codec. */
    const original = new TextEncoder().encode("state-sync-payload:".repeat(256));
    /** Raw DEFLATE vector generated outside the adapter under test. */
    const compressed = deflateRawSync(original);
    /** Browser-compatible codec under test. */
    const adapter = createFflateFrameCompressionAdapter();

    const decoded = await adapter.inflateRaw({
      input: compressed.buffer.slice(
        compressed.byteOffset,
        compressed.byteOffset + compressed.byteLength,
      ),
      expectedLength: original.byteLength,
      maxOutputLength: original.byteLength + 1,
    });

    expect(new Uint8Array(decoded)).toEqual(original);
    expect(decoded.byteLength).toBe(original.byteLength);
  });

  test("produces a raw DEFLATE frame that Node decodes byte-for-byte", async () => {
    /** Original bytes encoded by the browser-compatible codec. */
    const original = new TextEncoder().encode("terminal-history:".repeat(256));
    /** Browser-compatible codec under test. */
    const adapter = createFflateFrameCompressionAdapter();

    const compressed = await adapter.deflateRaw({ input: original.buffer, level: 1 });
    const decoded = inflateRawSync(new Uint8Array(compressed));
    /** Node Buffer normalized to the cross-runtime byte view asserted by the contract. */
    const decodedBytes = new Uint8Array(decoded.buffer, decoded.byteOffset, decoded.byteLength);

    expect(decodedBytes).toEqual(original);
  });

  test("rejects raw DEFLATE output larger than the authenticated length", async () => {
    /** Original bytes whose authenticated length will be intentionally understated. */
    const original = new TextEncoder().encode("oversized-state-sync:".repeat(256));
    /** Raw DEFLATE input produced by the independent Node codec. */
    const compressed = deflateRawSync(original);
    /** Browser-compatible codec under test. */
    const adapter = createFflateFrameCompressionAdapter();

    await expect(
      adapter.inflateRaw({
        input: compressed.buffer.slice(
          compressed.byteOffset,
          compressed.byteOffset + compressed.byteLength,
        ),
        expectedLength: original.byteLength - 1,
        maxOutputLength: original.byteLength,
      }),
    ).rejects.toThrow("Framed ciphertext decompressed length exceeds authenticated length");
  });

  test("rejects raw DEFLATE output shorter than the authenticated length", async () => {
    /** Original bytes whose authenticated length will be intentionally overstated. */
    const original = new TextEncoder().encode("truncated-state-sync:".repeat(256));
    /** Raw DEFLATE input produced by the independent Node codec. */
    const compressed = deflateRawSync(original);
    /** Browser-compatible codec under test. */
    const adapter = createFflateFrameCompressionAdapter();

    await expect(
      adapter.inflateRaw({
        input: compressed.buffer.slice(
          compressed.byteOffset,
          compressed.byteOffset + compressed.byteLength,
        ),
        expectedLength: original.byteLength + 1,
        maxOutputLength: original.byteLength + 2,
      }),
    ).rejects.toThrow("Framed ciphertext decompressed length is shorter than authenticated length");
  });

  test("accepts the one-byte sentinel above the maximum logical output", async () => {
    /** Maximum logical payload permitted by the framed compression contract. */
    const original = new Uint8Array(MAX_COMPRESSION_INPUT_BYTES).fill(0x2a);
    /** Raw DEFLATE input generated by the independent Node codec. */
    const compressed = deflateRawSync(original, { level: 1 });
    /** Browser-compatible codec under test. */
    const adapter = createFflateFrameCompressionAdapter();

    const decoded = await adapter.inflateRaw({
      input: compressed.buffer.slice(
        compressed.byteOffset,
        compressed.byteOffset + compressed.byteLength,
      ),
      expectedLength: original.byteLength,
      maxOutputLength: original.byteLength + 1,
    });

    expect(decoded.byteLength).toBe(MAX_COMPRESSION_INPUT_BYTES);
    expect(new Uint8Array(decoded)[0]).toBe(0x2a);
    expect(new Uint8Array(decoded)[decoded.byteLength - 1]).toBe(0x2a);
  });
});
